---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by NRC.
--- DateTime: 18/06/2022 23:45
---

fx_version "bodacious"
game "gta5"

ui_page "index.html"


shared_scripts {
    "config.lua"
}

client_scripts {
    "client/client.lua"
}

server_scripts {
    "server/server.lua"
}

files {
    "index.html",
    "style.css",
    "assets/index.js"
    
}